name: doteki

on:
  workflow_dispatch:
  schedule:
    - cron: "23 4 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install "doteki[all]"
      - run: doteki
      - name: commit changes
        run: |
          git config user.name "quueli"
          git config user.email "rampadian@mail.ru"
          git add README.md
          git diff --quiet --cached || git commit -m "refresh profile sections"
          git push
